name: checkout private repository ( pat )

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          # プライベートリポジトリを指定
          repository: koki-develop/private-repo-example
          # checkout 先のパスを指定
          path: ./private-repo-example
          # Personal Access Token を指定
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # プライベートリポジトリの中身を表示してみる
      - run: ls ./private-repo-example
